Repository 42-world/42world-Frontend, pull requests merged in 2022-07, with the labels that each got.

#66 Test: 테스트 및 CI 적용
  .github/workflows/test.yml
  package.json
  src/__test__/LoginButton.test.js
  src/setupTests.js
  yarn.lock
Labels: back log

#62 Feature/noti modal
  public/assets/comment.svg
  public/assets/like.svg
  src/common/PageLayout.jsx
  src/common/TopNav/components/NotiList.jsx
  src/common/TopNav/components/NotiModal.jsx
  src/common/TopNav/components/TopNav.jsx
  src/common/TopNav/components/UserItems.jsx
  src/store/notiModal.js
Labels: next upgrade

#70 Feature/donation
  public/assets/donation1.png
  public/assets/donation2.png
  public/assets/donation3.png
  src/Router.js
  src/components/pages/Donation.jsx
  src/components/pages/Mypage.jsx
Labels: enhancement

#90 Fix: index.html, favicon 경로 수정
  public/index.html
Labels: next upgrade

#93 Feat: background
  public/assets/main_background.jpeg
  public/assets/main_background.webp
  src/components/organisms/auth/Seoul42.jsx
  src/components/pages/Auth.jsx
  src/components/pages/login/Login.jsx
Labels: next upgrade
