Repository 42-world/42world-Frontend, pull requests merged in 2022-05, with the labels that each got.

#37 Feat/my article
  src/Router.js
  src/components/organisms/mypage/CharSelectModal.jsx
  src/components/organisms/mypage/MyArticleBoard.jsx
  src/components/organisms/mypage/MyArticlePageSelector.jsx
  src/components/organisms/mypage/MyArticlePreview.jsx
  src/components/organisms/mypage/MyProfile.jsx
  src/components/organisms/mypage/ProfileSection.jsx
  src/components/organisms/mypage/index.js
  src/components/pages/Mypage.jsx
  src/network/UserService.js
Labels: enhancement

#48 Feat: Create template.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/pull_request_template.md
Labels: documentation, enhancement

#45 Refactor: router
  .gitignore
  package.json
  src/App.js
  src/Reset.css
  src/Router.js
  src/common/PageLayout.jsx
  src/common/TopNav/components/Account.jsx
  src/common/TopNav/components/Logo.jsx
  src/common/TopNav/components/MenuItems.jsx
  src/common/TopNav/components/TopNav.jsx
  src/common/TopNav/components/UserItems.jsx
  src/common/TopNav/index.js
  src/common/TopNav/styled/Account.styled.js
  src/common/TopNav/styled/Logo.styled.js
  src/common/TopNav/styled/MenuItems.styled.js
  src/common/TopNav/styled/TopNav.styled.js
  src/common/TopNav/styled/index.js
  src/common/hooks/api/category.js
  src/components/organisms/SideNavigation.jsx
  src/components/organisms/TopNavOld.jsx
  src/components/organisms/auth/Seoul42.jsx
  src/components/organisms/login/LoginCheck.jsx
  src/components/organisms/mypage/AuthButton.jsx
  src/components/organisms/mypage/CharSelectModal.jsx
  src/components/organisms/mypage/Logout.jsx
  src/components/organisms/mypage/MyProfile.jsx
  src/components/pages/Auth.jsx
  src/components/pages/Login.jsx
  src/components/pages/Mypage.jsx
  src/index.js
  src/network/APIType.js
  src/store/user.js
  yarn.lock
Labels: enhancement, next upgrade
